Khdamat/Models/Worker.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Khdamat.Models
{
    public class Worker
    {
        [Key]
        [StringLength(maximumLength: 20)]
        [Required]
        public string Natoinal_ID { get; set; }
        public string Client_Email { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string Last_Name { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string Country { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string City { get; set; }
        [StringLength(maximumLength: 50)]
        public string Street { get; set; }
        [Required]
        [StringLength(maximumLength: 15)]
        [Phone]
        public string Phone { get; set; }
        [Required]
        public char Gender { get; set; }
        [Required]
        public DateTime Birth_Date { get; set; }
        public float Rating { get; set; }
    }
}

Khdamat/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Khdamat.Data;
using Khdamat.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Http;

namespace Khdamat.Controllers
{
    public class WorkersController : Controller
    {
        SqlCommand com = new SqlCommand();
        SqlConnection con = new SqlConnection();
        SqlDataReader dr;
        private readonly ApplicationDbContext _context;

        public WorkersController(ApplicationDbContext context)
        {
            _context = context;
            con.ConnectionString = Khdamat.Properties.Resources.ConnectionString;
        }

        // GET: Workers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Worker.ToListAsync());
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.Worker
                .FirstOrDefaultAsync(m => m.Natoinal_ID == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // GET: Workers/Register
        public IActionResult Register()
        {
            if (HttpContext.Session.GetString("Email") == null)
                return RedirectToAction("Register", "Accounts");
            if (HttpContext.Session.GetInt32("isWorker") != null)
                return RedirectToAction("Register", "Accounts");
            Worker worker = new Worker();
            return View(worker);
        }

        // POST: Workers/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([Bind("Natoinal_ID,Worker_Email,First_Name,Last_Name,Country,City,Street,Phone,Gender,Birth_Date")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.Session.GetString("Email") == null)
                    return RedirectToAction("Register", "Accounts");
                con.Open();
                com.Connection = con;
                com.CommandText = "INSERT INTO Worker (Natoinal_ID, Worker_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date) values ('"
                    + worker.Natoinal_ID + "','"
                    + HttpContext.Session.GetString("Email") + "','"
                    + worker.First_Name + "','"
                    + worker.Last_Name + "','"
                    + worker.Country + "','"
                    + worker.City + "','"
                    + worker.Street + "','"
                    + worker.Phone + "','"
                    + worker.Gender.ToString() + "','"
                    + worker.Birth_Date.ToString("yyyy-MM-dd")
                    + "');";
                try
                {
                    com.ExecuteNonQuery();
                    
                }
                catch
                {
                    TempData["AlertMessage"] = "هذا الرقم القومى مسجل من قبل";
                    return View(worker);
                }
                    com.CommandText = "UPDATE ACCOUNT SET Worker_b = '1' WHERE Email = '"
                        + HttpContext.Session.GetString("Email") + "';";
                    com.ExecuteNonQuery();
                    HttpContext.Session.SetInt32("isWorker", 1);
                    HttpContext.Session.SetString("FirstName", worker.First_Name.ToString());
                con.Close();
                return RedirectToAction("Index", "Home");
            }
            return View(worker);
        }


        // GET: Workers/profile
        public IActionResult profile()
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "SELECT Natoinal_ID, Worker_Email, F_Name, L_Name, Phone, Gender, Rating FROM Worker, Account WHERE Email = Worker_Email AND Email = '" + HttpContext.Session.GetString("Email") + " ';";
            dr = com.ExecuteReader();
            dr.Read();
            Worker worker = new Worker();
            worker.Natoinal_ID = dr["Natoinal_ID"].ToString();
            worker.First_Name = dr["F_Name"].ToString();
            worker.Last_Name = dr["L_Name"].ToString();
            worker.Client_Email = dr["Worker_Email"].ToString();
            worker.Phone = dr["Phone"].ToString();
            worker.Gender = dr["Gender"].ToString()[0];
            worker.Rating = (float)dr["Rating"].ToString()[0] - 48;
            dr.Close();
            con.Close();

            return View(worker);
        }


        // POST: Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Natoinal_ID,Client_Email,First_Name,Last_Name,Country,City,Street,Phone,Gender,Birth_Date,Rating")] Worker worker)
        {
            if (id != worker.Natoinal_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(worker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkerExists(worker.Natoinal_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        // GET: Workers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.Worker
                .FirstOrDefaultAsync(m => m.Natoinal_ID == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var worker = await _context.Worker.FindAsync(id);
            _context.Worker.Remove(worker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkerExists(string id)
        {
            return _context.Worker.Any(e => e.Natoinal_ID == id);
        }
        public IActionResult workersControl(string id)
        {
            con.Open();
            com.Connection = con;
            com.CommandType = System.Data.CommandType.StoredProcedure;
            com.CommandText = "WorkerControl";
            //com.CommandText = "SELECT Natoinal_ID, Worker_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date, Rating, Admin_b, S_Blocked,Supporter_b FROM Worker, Account WHERE Email = Worker_Email;";
            dr = com.ExecuteReader();
            com.CommandType = System.Data.CommandType.Text;
            List<WorkerDetails> workers = new List<WorkerDetails>();
            WorkerDetails workersDetails;
            while (dr.Read())
            {
                workersDetails = new WorkerDetails();
                workersDetails.worker.Natoinal_ID = dr["Natoinal_ID"].ToString();
                workersDetails.worker.Client_Email = dr["Worker_Email"].ToString();
                workersDetails.worker.First_Name = dr["F_Name"].ToString();
                workersDetails.worker.Last_Name = dr["L_Name"].ToString();
                workersDetails.worker.Country = dr["Country"].ToString();
                workersDetails.worker.City = dr["City"].ToString();
                workersDetails.worker.Street = dr["Street"].ToString();
                workersDetails.worker.Phone = dr["Phone"].ToString();
                workersDetails.worker.Gender = dr["Gender"].ToString()[0];
                workersDetails.worker.Birth_Date = ((DateTime)dr["Birth_Date"]);
                workersDetails.worker.Rating =float.Parse(dr["Rating"].ToString());
                if (dr["Admin_b"].ToString() == "True")
                    workersDetails.isAdmin = true;
                else
                    workersDetails.isAdmin = false;

                if (dr["S_Blocked"].ToString() == "True")
                    workersDetails.isBlocked = true;
                else
                    workersDetails.isBlocked = false;
                if (string.IsNullOrEmpty(dr["Supporter_b"].ToString()))
                {
                    workersDetails.isSupporter = false;
                }
                else if (dr["Supporter_b"].ToString() == "True")
                    workersDetails.isSupporter = true;
                else workersDetails.isSupporter = false;
                workers.Add(workersDetails);
            }
            dr.Close();
            con.Close();
            return View(workers);
        }

        public IActionResult BlockWorker(Worker c)
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE Account SET S_Blocked= '" + true + "' WHERE Email='" + c.Client_Email + "';";
            com.ExecuteNonQuery();

Khdamat/Views/Workers/Register.cshtml
@model Khdamat.Models.Worker

@{
    ViewData["Title"] = "register";
}

@*<h1>Create</h1>

<h4>Worker</h4>
<hr />*@
<div class="row">
    <div class="col-md-4 register">
        <form asp-action="register">
            <h2 class="makeflex graycolor logofont">خدمات</h2>
            <h2 class="makeflex">انشاء حساب جديد</h2>
            <hr />
            @if (TempData["AlertMessage"] != null)
                {
                    <div class="alert alert-danger" >
                        @TempData["AlertMessage"]
                    </div>
                }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*   <label asp-for="Natoinal_ID" class="control-label"></label>*@
                <input asp-for="Natoinal_ID" class="form-control" placeholder="الرقم القومي" />
                <span asp-validation-for="Natoinal_ID" class="text-danger"></span>
            </div>
            <!--<div class="form-group">-->
                @*  <label asp-for="Client_Email" class="control-label"></label>*@
                <!--<input asp-for="Client_Email" class="form-control" placeholder="البريد الالكتروني للزبون" />
                <span asp-validation-for="Client_Email" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                @*<label asp-for="First_Name" class="control-label"></label>*@
                <input asp-for="First_Name" class="form-control" placeholder="الاسم الاول" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Last_Name" class="control-label"></label>*@
                <input asp-for="Last_Name" class="form-control" placeholder="الاسم الاخير" />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Country" class="control-label"></label>*@
                <input asp-for="Country" class="form-control" placeholder="البلد" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="City" class="control-label"></label>*@
                <input asp-for="City" class="form-control" placeholder="المدينة" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Street" class="control-label"></label>*@
                <input asp-for="Street" class="form-control" placeholder="الشارع" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Phone" class="control-label"></label>*@
                <input asp-for="Phone" class="form-control" placeholder="رقم الهاتف" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Birth_Date" class="control-label"></label>*@
                <input asp-for="Birth_Date" class="form-control" />
                <span asp-validation-for="Birth_Date" class="text-danger"></span>
            </div>

            <div class="typeofuser">
                <div class="form-group form-check">
                    <label class="form-check-label makeflex ">

                        @*<div><input class="form-check-input" asp-for="IsWorker" /></div>*@
                        <div> <input type="radio" name="gender" value="M" asp-for="Gender" /></div>
                        <div class="marginright">ذكر</div>
                        @*@Html.DisplayNameFor(model => model.IsWorker)*@
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label makeflex ">

                        @*<div> <input class="form-check-input" asp-for="IsClient" /></div>*@
                        <div> <input type="radio" name="gender" value="F" asp-for="Gender" /></div>
                        <div class="marginright">انثي</div>

                        @*@Html.DisplayNameFor(model => model.IsClient)*@
                    </label>
                </div>
            </div>

            <!--<div class="form-group">-->
            @*<label asp-for="Gender" class="control-label"></label>*@
            <!--<input asp-for="Gender" class="form-control" placeholder="النوع" />
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>-->
            @*<div class="form-group">
            <label asp-for="Rating" class="control-label"></label>
            <input asp-for="Rating" class="form-control" />
            <span asp-validation-for="Rating" class="text-danger"></span>
        </div>*@
            <div class="form-group center">
                <input type="submit" value="انشاء حساب" class="btn btn-primary defultbutton" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Khdamat/Views/Workers/profile.cshtml
@model Khdamat.Models.Worker
@{
    ViewData["Title"] = "profile";
}

<h2 class="makeflex">معلومات الحساب </h2>
<hr />
<div>
    <div class="makeflex">
        <p class="rigthTitle">الاسم:</p>
        <p class="leftInfo">@Model.First_Name @Model.Last_Name</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">النوع:</p>
        <p class="leftInfo">
            @((Model.Gender == 'M') ? "ذكر" : "انثى")
            </p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">البريد الالكتروني:</p>
        <p class="leftInfo">@Model.Client_Email</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">رقم الهاتف:</p>
        <p class="leftInfo">@Model.Phone</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">التقييم:</p>
        <p class="leftInfo">@Model.Rating</p>
    </div>
    <div class="makeflex">
        <a class="btn-primary defultbutton rightButton" asp-area="" asp-controller="Accounts" asp-action="changePassword">تغيير كلمة المرور</a>

        <a class="btn-primary defultbutton leftButton" href="@Url.Action("showReviews","Reviews", new {Model.Natoinal_ID})">الريفيوهات</a>
    </div>

</div>

Khdamat/Views/Workers/showReviews.cshtml
@*@{
    ViewData["Title"] = "showReviews";
}

@foreach (var item in Model)
{


    <div>
        <div class="makeflex">
            <p class="rigthTitle">اسم الزبون:</p>
            <p class="leftInfo">حط اسم الراجل اللي عامل الريفيو هنا</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الريفيو:</p>
            <p class="leftInfo">حط الريفيو</p>
        </div>
      

    </div>
    <hr />
}*@

Khdamat/Views/Workers/workersControl.cshtml
@model List<Khdamat.Models.WorkerDetails>
@using Microsoft.AspNetCore.Http;
@using System.Globalization

@{
    ViewData["Title"] = "workersControl";
}

<h2 class="makeflex">التحكم في العمال</h2>
<hr />


    @foreach (var item in Model)
   {


    <div>
        <div class="makeflex">
            <p class="rigthTitle">الاسم الاول:</p>
            <p class="leftInfo">@item.worker.First_Name</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الاسم الاخير:</p>
            <p class="leftInfo">@item.worker.Last_Name</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">البريد الالكتروني:</p>
            <p class="leftInfo">@item.worker.Client_Email</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الرقم القومي:</p>
            <p class="leftInfo">@item.worker.Natoinal_ID</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">البلد:</p>
            <p class="leftInfo">@item.worker.Country</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">المدينة:</p>
            <p class="leftInfo">@item.worker.City</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الشارع:</p>
            <p class="leftInfo">@item.worker.Street</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">رقم الهاتف:</p>
            <p class="leftInfo">@item.worker.Phone</p>
        </div>

        <div class="makeflex">
            <p class="rigthTitle">النوع:</p>
            <p class="leftInfo">@item.worker.Gender</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">تاريخ الميلاد:</p>
            <p class="leftInfo">@item.worker.Birth_Date.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture)</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle"> التقييم:</p>
            <p class="leftInfo">@item.worker.Rating</p>
        </div>

        @if (item.isAdmin == false && item.isSupporter == false)
        {
            <div class="makeflex">
                @if (Context.Session.GetInt32("isAdmin") == 1)
                {
                    <a class="btn-primary defultbutton rightButton" href=@Url.Action("protosupporter","Workers",item.worker)>خليه السابورتر</a>
                }
                @if (item.isBlocked == false)
                {
                    <a class="btn-primary defultbutton leftButton" href="@Url.Action("BlockWorker","Workers", item.worker)">بلوك</a>
                }

                @if (item.isBlocked == true)
                {
                    <a class="btn-primary defultbutton leftButton" href="@Url.Action("UNBlockWorker","Workers", item.worker)">ازل البلوك</a>
                }

            </div>
        }

        @if (item.isAdmin == true || item.isSupporter == true)
        {
        <div class="makeflex">
            <p class="rigthTitle">ادمن/سابورتر</p>
        </div>
         }

        </div>
        <hr />
    }


    
       