Khdamat/Models/Supporter.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Khdamat.Models
{
    public class Supporter
    {
        [Key]
        [StringLength(maximumLength: 20)]
        [Required]
        public string Natoinal_ID { get; set; }
        public string Supporter_Email { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string Last_Name { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string Country { get; set; }
        [Required]
        [StringLength(maximumLength: 20)]
        public string City { get; set; }
        [StringLength(maximumLength: 50)]
        public string Street { get; set; }
        [Required]
        [StringLength(maximumLength: 15)]
        [Phone]
        public string Phone { get; set; }
        [Required]
        public char Gender { get; set; }
        [Required]
        public DateTime Birth_Date { get; set; }

        [Required]
        [StringLength(maximumLength: 20)]
        public string Admin_ID { get; set; }
    }
}

Khdamat/Controllers/SupportersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Khdamat.Data;
using Khdamat.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Http;

namespace Khdamat.Controllers
{
    public class SupportersController : Controller
    {
        SqlCommand com = new SqlCommand();
        SqlConnection con = new SqlConnection();
        SqlDataReader dr;
        private readonly ApplicationDbContext _context;

        public SupportersController(ApplicationDbContext context)
        {
            _context = context;
            con.ConnectionString = Khdamat.Properties.Resources.ConnectionString;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult supportersControl(string id)
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "SELECT Natoinal_ID, Supporter_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date, Admin_ID, Admin_b, S_Blocked,Supporter_b FROM Supporter, Account WHERE Email = Supporter_Email;";
            dr = com.ExecuteReader();
            List<SupportersDetails> supporters = new List<SupportersDetails>();
            SupportersDetails supportersDetails;
            while (dr.Read())
            {
                supportersDetails = new SupportersDetails();
                supportersDetails.supporter.Natoinal_ID = dr["Natoinal_ID"].ToString();
                supportersDetails.supporter.Supporter_Email = dr["Supporter_Email"].ToString();
                supportersDetails.supporter.First_Name = dr["F_Name"].ToString();
                supportersDetails.supporter.Last_Name = dr["L_Name"].ToString();
                supportersDetails.supporter.Country = dr["Country"].ToString();
                supportersDetails.supporter.City = dr["City"].ToString();
                supportersDetails.supporter.Street = dr["Street"].ToString();
                supportersDetails.supporter.Phone = dr["Phone"].ToString();
                supportersDetails.supporter.Gender = dr["Gender"].ToString()[0];
                supportersDetails.supporter.Birth_Date = ((DateTime)dr["Birth_Date"]);
                supportersDetails.supporter.Admin_ID = dr["Admin_ID"].ToString();
                if (dr["Admin_b"].ToString() == "True")
                    supportersDetails.isAdmin = true;
                else
                    supportersDetails.isAdmin = false;

                if (dr["S_Blocked"].ToString() == "True")
                    supportersDetails.isBlocked = true;
                else
                    supportersDetails.isBlocked = false;
                if (string.IsNullOrEmpty(dr["Supporter_b"].ToString()))
                {
                    supportersDetails.isSupporter = false;
                }
                else if (dr["Supporter_b"].ToString() == "True")
                    supportersDetails.isSupporter = true;
                else supportersDetails.isSupporter = false;
                supporters.Add(supportersDetails);
            }
            dr.Close();
            con.Close();
            return View(supporters);
        }

        public IActionResult BlockSupporter(Supporter c)
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE Account SET S_Blocked= '" + true + "' WHERE Email='" + c.Supporter_Email + "';";
            com.ExecuteNonQuery();
            com.CommandText = "SELECT Natoinal_ID, Supporter_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date, Admin_ID, Admin_b, S_Blocked,Supporter_b FROM Supporter, Account WHERE Email = Supporter_Email;";
            dr = com.ExecuteReader();
            List<SupportersDetails> supporters = new List<SupportersDetails>();
            SupportersDetails supportersDetails;
            while (dr.Read())
            {
                supportersDetails = new SupportersDetails();
                supportersDetails.supporter.Natoinal_ID = dr["Natoinal_ID"].ToString();
                supportersDetails.supporter.Supporter_Email = dr["Supporter_Email"].ToString();
                supportersDetails.supporter.First_Name = dr["F_Name"].ToString();
                supportersDetails.supporter.Last_Name = dr["L_Name"].ToString();
                supportersDetails.supporter.Country = dr["Country"].ToString();
                supportersDetails.supporter.City = dr["City"].ToString();
                supportersDetails.supporter.Street = dr["Street"].ToString();
                supportersDetails.supporter.Phone = dr["Phone"].ToString();
                supportersDetails.supporter.Gender = dr["Gender"].ToString()[0];
                supportersDetails.supporter.Birth_Date = ((DateTime)dr["Birth_Date"]);
                supportersDetails.supporter.Admin_ID = dr["Admin_ID"].ToString();
                if (dr["Admin_b"].ToString() == "True")
                    supportersDetails.isAdmin = true;
                else
                    supportersDetails.isAdmin = false;

                if (dr["S_Blocked"].ToString() == "True")
                    supportersDetails.isBlocked = true;
                else
                    supportersDetails.isBlocked = false;
                if (string.IsNullOrEmpty(dr["Supporter_b"].ToString()))
                {
                    supportersDetails.isSupporter = false;
                }
                else if (dr["Supporter_b"].ToString() == "True")
                    supportersDetails.isSupporter = true;
                else supportersDetails.isSupporter = false;
                supporters.Add(supportersDetails);
            }
            dr.Close();
            con.Close();
            return View("supportersControl", supporters);
        }

        public IActionResult UNBlockSupporter(Supporter c)
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE Account SET S_Blocked= '" + false + "' WHERE Email='" + c.Supporter_Email + "';";
            com.ExecuteNonQuery();
            com.CommandText = "SELECT Natoinal_ID, Supporter_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date, Admin_ID, Admin_b, S_Blocked,Supporter_b FROM Supporter, Account WHERE Email = Supporter_Email;";
            dr = com.ExecuteReader();
            List<SupportersDetails> supporters = new List<SupportersDetails>();
            SupportersDetails supportersDetails;
            while (dr.Read())
            {
                supportersDetails = new SupportersDetails();
                supportersDetails.supporter.Natoinal_ID = dr["Natoinal_ID"].ToString();
                supportersDetails.supporter.Supporter_Email = dr["Supporter_Email"].ToString();
                supportersDetails.supporter.First_Name = dr["F_Name"].ToString();
                supportersDetails.supporter.Last_Name = dr["L_Name"].ToString();
                supportersDetails.supporter.Country = dr["Country"].ToString();
                supportersDetails.supporter.City = dr["City"].ToString();
                supportersDetails.supporter.Street = dr["Street"].ToString();
                supportersDetails.supporter.Phone = dr["Phone"].ToString();
                supportersDetails.supporter.Gender = dr["Gender"].ToString()[0];
                supportersDetails.supporter.Birth_Date = ((DateTime)dr["Birth_Date"]);
                supportersDetails.supporter.Admin_ID = dr["Admin_ID"].ToString();
                if (dr["Admin_b"].ToString() == "True")
                    supportersDetails.isAdmin = true;
                else
                    supportersDetails.isAdmin = false;

                if (dr["S_Blocked"].ToString() == "True")
                    supportersDetails.isBlocked = true;
                else
                    supportersDetails.isBlocked = false;
                if (string.IsNullOrEmpty(dr["Supporter_b"].ToString()))
                {
                    supportersDetails.isSupporter = false;
                }
                else if (dr["Supporter_b"].ToString() == "True")
                    supportersDetails.isSupporter = true;
                else supportersDetails.isSupporter = false;
                supporters.Add(supportersDetails);
            }
            dr.Close();
            con.Close();
            return View("SupportersControl", supporters);
        }

        public IActionResult protoAdmin(Supporter c)
        {
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE Account SET Admin_b='" + true + "' WHERE Email='" + c.Supporter_Email + "';";
            com.ExecuteNonQuery();
            com.CommandText = "INSERT INTO Administrator (Natoinal_ID, Admin_Email, F_Name, L_Name, Country, City, Street, Phone, Gender) values ('"
                    + c.Natoinal_ID + "','"
                    + c.Supporter_Email + "','"
                    + c.First_Name + "','"
                    + c.Last_Name + "','"
                    + c.Country + "','"
                    + c.City + "','"
                    + c.Street + "','"
                    + c.Phone + "','"
                    + c.Gender.ToString()
                    + "');";
            com.ExecuteNonQuery();
            com.CommandText = "SELECT Natoinal_ID, Supporter_Email, F_Name, L_Name, Country, City, Street, Phone, Gender, Birth_Date, Admin_ID, Admin_b, S_Blocked,Supporter_b FROM Supporter, Account WHERE Email = Supporter_Email;";
            dr = com.ExecuteReader();
            List<SupportersDetails> supporters = new List<SupportersDetails>();
            SupportersDetails supportersDetails;
            while (dr.Read())
            {
                supportersDetails = new SupportersDetails();
                supportersDetails.supporter.Natoinal_ID = dr["Natoinal_ID"].ToString();

Khdamat/Views/Supporters/Delete.cshtml
@model Khdamat.Models.Worker

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Worker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client_Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client_Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.First_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Last_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birth_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birth_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Natoinal_ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Khdamat/Views/Supporters/Details.cshtml
@model Khdamat.Models.Worker

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Worker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client_Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client_Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.First_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Last_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birth_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birth_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Natoinal_ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Khdamat/Views/Supporters/Edit.cshtml
@model Khdamat.Models.Worker

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Worker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Natoinal_ID" />
            <div class="form-group">
                <label asp-for="Client_Email" class="control-label"></label>
                <input asp-for="Client_Email" class="form-control" />
                <span asp-validation-for="Client_Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="First_Name" class="control-label"></label>
                <input asp-for="First_Name" class="form-control" />
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" class="control-label"></label>
                <input asp-for="Last_Name" class="form-control" />
                <span asp-validation-for="Last_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birth_Date" class="control-label"></label>
                <input asp-for="Birth_Date" class="form-control" />
                <span asp-validation-for="Birth_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Khdamat/Views/Supporters/Index.cshtml
@model IEnumerable<Khdamat.Models.Worker>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Client_Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birth_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Client_Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.First_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Last_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birth_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Natoinal_ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Natoinal_ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Natoinal_ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Khdamat/Views/Supporters/SupportersControl.cshtml
@model List<Khdamat.Models.SupportersDetails>
@using Microsoft.AspNetCore.Http;
@using System.Globalization

@{
    ViewData["Title"] = "workersControl";
}

<h2 class="makeflex">التحكم في السابورترز</h2>
<hr />


    @foreach (var item in Model)
   {


    <div>
        <div class="makeflex">
            <p class="rigthTitle">الاسم الاول:</p>
            <p class="leftInfo">@item.supporter.First_Name</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الاسم الاخير:</p>
            <p class="leftInfo">@item.supporter.Last_Name</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">البريد الالكتروني:</p>
            <p class="leftInfo">@item.supporter.Supporter_Email</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الرقم القومي:</p>
            <p class="leftInfo">@item.supporter.Natoinal_ID</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">البلد:</p>
            <p class="leftInfo">@item.supporter.Country</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">المدينة:</p>
            <p class="leftInfo">@item.supporter.City</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">الشارع:</p>
            <p class="leftInfo">@item.supporter.Street</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">رقم الهاتف:</p>
            <p class="leftInfo">@item.supporter.Phone</p>
        </div>

        <div class="makeflex">
            <p class="rigthTitle">النوع:</p>
            <p class="leftInfo">@item.supporter.Gender</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle">تاريخ الميلاد:</p>
            <p class="leftInfo">@item.supporter.Birth_Date.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture)</p>
        </div>
        <div class="makeflex">
            <p class="rigthTitle"> الادمن الى وظفه:</p>
            <p class="leftInfo">@item.supporter.Admin_ID</p>
        </div>

        @if (item.isAdmin == false)
        {
            <div class="makeflex">
                @if (Context.Session.GetInt32("isAdmin") == 1)
                {
                    <a class="btn-primary defultbutton rightButton" href=@Url.Action("protoAdmin","Supporters",item.supporter)>خليه ادمن</a>
                }
                 @if (Context.Session.GetInt32("isAdmin") == 1)
                {
                    <a class="btn-primary defultbutton leftButton" href=@Url.Action("demofromsupporter","Supporters",item.supporter)>شيل منه السابورت</a>
                }
                @if (item.isBlocked == false)
                {
                    <a class="btn-primary defultbutton leftButton" href="@Url.Action("BlockSupporter","Supporters", item.supporter)">بلوك</a>
                }

                @if (item.isBlocked == true)
                {
                    <a class="btn-primary defultbutton leftButton" href="@Url.Action("UNBlockSupporter","Supporters", item.supporter)">ازل البلوك</a>
                }

            </div>
        }

        @if (item.isAdmin == true)
        {
        <div class="makeflex">
            <p class="rigthTitle">ادمن</p>
        </div>
         }

        </div>
        <hr />
    }


    
       

Khdamat/Views/Supporters/profile.cshtml
@model Khdamat.Models.Worker
@{
    ViewData["Title"] = "profile";
}

<h2 class="makeflex">معلومات الحساب </h2>
<hr />
<div>
    <div class="makeflex">
        <p class="rigthTitle">الاسم:</p>
        <p class="leftInfo">@Model.First_Name @Model.Last_Name</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">النوع:</p>
        <p class="leftInfo">
            @((Model.Gender == 'M') ? "ذكر" : "انثى")
            </p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">البريد الالكتروني:</p>
        <p class="leftInfo">@Model.Client_Email</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">رقم الهاتف:</p>
        <p class="leftInfo">@Model.Phone</p>
    </div>
    <div class="makeflex">
        <p class="rigthTitle">التقييم:</p>
        <p class="leftInfo">@Model.Rating</p>
    </div>
    <div class="makeflex">
    <a class="defultbutton rightButton" asp-area="" asp-controller="Accounts" asp-action="changePassword">تغيير كلمة المرور</a>
    </div>

</div>